#!/bin/bash
# Find all files with .gif extension, including hidden files
find . -type f -iname '*.gif' -printf '%f\0' |
# Remove file extension and sort case-insensitively by byte values
sed -z 's/\.gif\0/\0/' | LC_ALL=C sort -zfi |
# Print each file name on a new line
tr '\0' '\n'
