#!/usr/bin/env bash
#SSH client configaration
Host *
    PasswordAuthentication no
    IdentifyFile ~/.ssh/school
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
